version: "3"

services:
  ingestionapi:
    build:
      context: .
      dockerfile: ./src/Ingestion.API/Dockerfile
    image: ingestionapi
    ports:
      - 5000:5000
  calcapi:
    build: ./src/Calculation.API
    image: calculationapi
    ports:
      - 8000:8000